apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/broadcaster
  newTag: eb39d0b1a9d352a70e82ccb545760cd6cdeee898
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-app
  newTag: eb39d0b1a9d352a70e82ccb545760cd6cdeee898
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-backend
  newTag: eb39d0b1a9d352a70e82ccb545760cd6cdeee898
- name: PROJECT/TODO_CRON
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-cron
  newTag: eb39d0b1a9d352a70e82ccb545760cd6cdeee898
