apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/broadcaster
  newTag: af2d33c93707b3f40db57b52bf2404ca2f5be004
- name: PROJECT/TODO_APP
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-app
  newTag: af2d33c93707b3f40db57b52bf2404ca2f5be004
- name: PROJECT/TODO_BACKEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-backend
  newTag: af2d33c93707b3f40db57b52bf2404ca2f5be004
- name: PROJECT/TODO_CRON
  newName: europe-north1-docker.pkg.dev/dwk-gke-233649/dwk-repository/todo-cron
  newTag: af2d33c93707b3f40db57b52bf2404ca2f5be004
