apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: project-files
          persistentVolumeClaim:
            claimName: project-pvc
      containers:
        - name: todo-app
          image: PROJECT/TODO_APP
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          env:
            - name: PORT
              value: "3000"
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:3000"
            - name: PICSUM_URL
              value: "https://picsum.photos/1200"
          volumeMounts:
            - name: project-files
              mountPath: /usr/src/app/files
