apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/todo-app-pvc.yaml
  - manifests/todo-postgres.yaml
  - manifests/todo-backend-deployment.yaml
  - manifests/todo-backend-service.yaml
  - manifests/broadcaster-deployment.yaml
  - manifests/todo-app-deployment.yaml
  - manifests/todo-app-service.yaml
  - manifests/todo-app-ingress.yaml
  - manifests/todo-cronjob.yaml
  - manifests/todo-backup-cronjob.yaml
